version: '3.8'
services:
  linux:
    build:
      context: chrobalt/docker/linux
      cache_from:
        - ghcr.io/youtube/cobalt/linux:latest
      args:
        # Should match version pinned by Starboard
        - STARBOARD_CLANG_VER=${STARBOARD_CLANG_VER:-17-init-8029-g27f27d15-3}
    image: ghcr.io/youtube/cobalt/linux:latest
    platform: linux/amd64
    environment:
      - DEPOT_TOOLS_UPDATE=0
